name = "kotlin-khaos-api"
main = "src/index.ts"
compatibility_date = "2023-09-18"
workers_dev = false

routes = [{ pattern = "kotlin-khaos-api.maximoguk.com", custom_domain = true }]

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/kv
kv_namespaces = [{ binding = "CONVERSATIONS", id = "f0b4465a70524baf8cd8a3c8087606c2", preview_id = "f0b4465a70524baf8cd8a3c8087606c2" }]
